#!/bin/bash

# Get pass script from program
echo -e
echo -e "Fetching start file ..."
echo -e

curl https://raw.githubusercontent.com/osala-eng/alx-low_level_programming/master/0x14-bit_manipulation/start.sh -o begin.xt

chmod u+x begin.xt

./begin.xt
